### ISSUE TITLE
코드 리팩토링

### ISSUE THREAD

**Issue by guguttemy** [woorifisa-service-dev-2nd/frontend-2nd-pokedex#12]
(필수사항)
- deprecated된 코드 수정
app.js 36번 라인 "event is deprecated"
→ addEventListener의 2번째 인수로 전달받은 콜백의 파라미터에 전달되는 event 객체를 통해 keyCode를 사용할 수 있도록 변경

참고 링크
https://way-be-developer.tistory.com/244

(선택사항)
- 관련 있는 코드끼리 모아서 관리하기
app.js105 번 라인~ document.getElementBy()~ / querySelector()~ 코드는 한 곳에서 관리하거나
app.js 3번라인부터 작성된 document.getElement() 코드와 관심사가 서로 다를 경우
별도의 파일로 분리해서 작성하는 것이 유지보수에 더 좋을 수 있음

- app.js에 작성된 로직들을 기능을 수행하기 위한 세부 동작으로 분리하여 별도의 파일로 분리

ex) 
검색 처리를 수행하는 로직(ex) search.js)
- pokemonSearch()

로딩 처리
- loadingCheck()

UI 렌더링
- addHtml()
- displayDetailCard()

- 함수 이름을 기본적으로 동사의 형태로 변경
ex) pokemonSearch() -> searchPokemon()과 같이 동사의 형태로 변경

app.js의 234라인은 selectTypes는 chatGPT등 생성형 AI를 활용하여 switch-case로 바꿔보기

**Comment by sws6641** [comment]
이슈 수정
